// Class: ReadRuleFit
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : RuleFit::RuleFit
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/09       [336393]
Creator        : rute
Date           : Sun Sep 11 13:56:26 2016
Host           : Linux ui6-atlas.lip.pt 2.6.32-358.6.2.el6.x86_64 #1 SMP Thu May 16 20:59:36 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /u/home/calo/rute/EstagioATLAScoded/TMVAproject
Training events: 6000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "True" [Print method-specific help message]
GDTau: "-1.000000e+00" [Gradient-directed (GD) path: default fit cut-off]
GDTauPrec: "1.000000e-02" [GD path: precision of tau]
GDStep: "1.000000e-02" [GD path: step size]
GDNSteps: "10000" [GD path: number of steps]
GDErrScale: "1.020000e+00" [Stop scan when error > scale*errmin]
fEventsMin: "1.000000e-02" [Minimum fraction of events in a splittable node]
fEventsMax: "5.000000e-01" [Maximum fraction of events in a splittable node]
nTrees: "20" [Number of trees in forest.]
RuleMinDist: "1.000000e-03" [Minimum distance between rules]
MinImp: "1.000000e-03" [Minimum rule importance accepted]
Model: "modrulelinear" [Model to be used]
RuleFitModule: "rftmva" [Which RuleFit module to use]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
LinQuantile: "2.500000e-02" [Quantile of linear terms (removes outliers)]
GDPathEveFrac: "5.000000e-01" [Fraction of events used for the path search]
GDValidEveFrac: "5.000000e-01" [Fraction of events used for the validation]
ForestType: "adaboost" [Method to use for forest generation (AdaBoost or RandomForest)]
RFWorkDir: "./rulefit" [Friedman's RuleFit module (RFF): working dir]
RFNrules: "2000" [RFF: Mximum number of rules]
RFNendnodes: "4" [RFF: Average number of end nodes]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 4
var1+var2                     myvar1                        myvar1                        myvar1                                                          'F'    [-8.96602058411,7.69307804108]
var1-var2                     myvar2                        myvar2                        Expression 2                                                    'F'    [-4.08540010452,4.0258936882]
var3                          var3                          var3                          Variable 3                    units                             'F'    [-5.05078554153,4.35967063904]
var4                          var4                          var4                          Variable 4                    units                             'F'    [-5.95050764084,4.92254400253]
NSpec 2
var1*2                        spec1                         spec1                         Spectator 1                   units                             'F'    [-9.91655540466,9.52782058716]
var1*3                        spec2                         spec2                         Spectator 2                   units                             'F'    [-14.874833107,14.2917308807]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadRuleFit : public IClassifierReader {

 public:

   // constructor
   ReadRuleFit( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadRuleFit" ),
        fNvars( 4 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "var1+var2", "var1-var2", "var3", "var4" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadRuleFit() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[4];
   double fVmax[4];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[4];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   // not implemented for class: "ReadRuleFit"
};
void   ReadRuleFit::Initialize(){}
void   ReadRuleFit::Clear(){}
double ReadRuleFit::GetMvaValue__( const std::vector<double>& inputValues ) const {
   double rval=2.071262752;
   //
   // here follows all rules ordered in importance (most important first)
   // at the end of each line, the relative importance of the rule is given
   //
   if ((inputValues[0]<1.357761383)&&(inputValues[3]<-0.2550996244)) rval+=-0.4950892475;   // importance = 0.496
   if ((-0.2398260683<inputValues[0])) rval+=-0.4147339104;   // importance = 0.428
   if ((inputValues[3]<1.298193455)) rval+=-0.4933475131;   // importance = 0.395
   if ((inputValues[1]<-0.05838980153)&&(inputValues[3]<0.7804290652)) rval+=-0.3135178376;   // importance = 0.308
   if ((inputValues[2]<-0.4694648087)&&(inputValues[3]<-1.290628314)) rval+=-0.4334252877;   // importance = 0.300
   if ((inputValues[0]<2.169221878)&&(-1.465849876<inputValues[2])&&(inputValues[3]<0.6051196456)) rval+=-0.290066272;   // importance = 0.299
   if ((-1.67862308<inputValues[0])&&(inputValues[0]<0.2449699789)&&(0.003888924839<inputValues[3])) rval+=0.3848189932;   // importance = 0.275
   if ((-1.114703774<inputValues[0])&&(-0.9953834414<inputValues[1])) rval+=-0.2659059851;   // importance = 0.271
   if ((-1.017732859<inputValues[2])) rval+=-0.3330263728;   // importance = 0.259
   if ((inputValues[1]<0.5496249199)&&(inputValues[2]<0.3402785659)&&(inputValues[3]<-0.6145658493)) rval+=-0.2947607566;   // importance = 0.241
   if ((0.5496249199<inputValues[1])) rval+=-0.2301527157;   // importance = 0.221
   if ((-0.05838980153<inputValues[1])&&(inputValues[3]<0.7804290652)) rval+=-0.2015735395;   // importance = 0.200
   if ((-0.05838980153<inputValues[1])&&(inputValues[2]<0.9103753567)&&(inputValues[3]<0.7804290652)) rval+=-0.1958897003;   // importance = 0.193
   if ((inputValues[1]<0.5496249199)&&(0.3402785659<inputValues[2])) rval+=-0.1991871316;   // importance = 0.185
   if ((inputValues[1]<0.5496249199)&&(inputValues[2]<0.3402785659)&&(-0.6145658493<inputValues[3])) rval+=0.208502015;   // importance = 0.179
   if ((inputValues[2]<-1.017732859)) rval+=-0.182572216;   // importance = 0.142
   if ((-1.03311646<inputValues[0])&&(-0.5258482099<inputValues[1])&&(inputValues[1]<0.5496249199)) rval+=-0.1497721754;   // importance = 0.137
   if ((inputValues[0]<-0.2398260683)&&(inputValues[2]<0.6768341064)) rval+=-0.1159902354;   // importance = 0.119
   if ((-0.2398260683<inputValues[0])&&(inputValues[1]<-0.1328951567)) rval+=-0.1288532561;   // importance = 0.116
   if ((inputValues[0]<-0.2398260683)) rval+=-0.1008646784;   // importance = 0.104
   if ((inputValues[1]<0.5496249199)&&(inputValues[2]<0.3402785659)) rval+=-0.08625874154;   // importance = 0.088
   if ((inputValues[0]<0.9430016279)&&(-0.9953834414<inputValues[1])) rval+=0.05890312635;   // importance = 0.060
   if ((inputValues[1]<-0.6091313362)) rval+=-0.06175332135;   // importance = 0.059
   if ((inputValues[0]<-1.03311646)&&(inputValues[1]<0.5496249199)) rval+=0.05757322056;   // importance = 0.046
   if ((-1.290628314<inputValues[3])) rval+=-0.0573640104;   // importance = 0.041
   if ((-0.9482207298<inputValues[0])&&(-0.9953834414<inputValues[1])&&(-1.465849876<inputValues[2])&&(0.07701025903<inputValues[3])) rval+=-0.03850464613;   // importance = 0.039
   if ((-0.725399375<inputValues[0])&&(inputValues[0]<-0.1289403141)&&(inputValues[3]<-0.7728639841)) rval+=-0.09816225295;   // importance = 0.029
   if ((-0.9953834414<inputValues[1])&&(-1.465849876<inputValues[2])&&(0.07701025903<inputValues[3])) rval+=0.0278835688;   // importance = 0.029
   if ((inputValues[0]<2.169221878)&&(-1.465849876<inputValues[2])&&(inputValues[2]<0.4989257455)&&(inputValues[3]<0.6051196456)) rval+=-0.02325076355;   // importance = 0.024
   if ((inputValues[1]<0.4310674071)&&(-0.8670438528<inputValues[2])&&(inputValues[2]<1.141957879)&&(0.408131361<inputValues[3])&&(inputValues[3]<0.7424910665)) rval+=0.04670175945;   // importance = 0.022
   if ((0.5496249199<inputValues[1])&&(inputValues[1]<1.046367168)) rval+=-0.0300849112;   // importance = 0.022
   if ((0.4310674071<inputValues[1])&&(-0.8670438528<inputValues[2])&&(inputValues[2]<1.141957879)&&(0.408131361<inputValues[3])&&(inputValues[3]<0.7424910665)) rval+=0.04756764896;   // importance = 0.016
   if ((1.508122206<inputValues[0])&&(inputValues[0]<2.169221878)&&(-1.465849876<inputValues[2])&&(inputValues[3]<0.6051196456)) rval+=-0.07200135691;   // importance = 0.014
   if ((inputValues[1]<-0.9953834414)&&(-1.465849876<inputValues[2])&&(0.6051196456<inputValues[3])) rval+=-0.02687795724;   // importance = 0.014
   if ((-1.77317822<inputValues[0])&&(-0.6091313362<inputValues[1])&&(1.050306082<inputValues[3])) rval+=0.01691535293;   // importance = 0.013
   if ((inputValues[0]<-0.9482207298)&&(-0.9953834414<inputValues[1])&&(-1.465849876<inputValues[2])&&(0.07701025903<inputValues[3])) rval+=0.06638821493;   // importance = 0.013
   if ((inputValues[1]<-0.6091313362)&&(-0.1953787357<inputValues[3])) rval+=-0.007168747306;   // importance = 0.006
   if ((-0.4694648087<inputValues[2])&&(inputValues[3]<-1.290628314)) rval+=-0.02480929074;   // importance = 0.005
   if ((inputValues[0]<-0.2398260683)&&(0.6768341064<inputValues[2])) rval+=0.01512555695;   // importance = 0.004
   if ((-1.017732859<inputValues[2])&&(1.243130803<inputValues[3])) rval+=-0.003897308692;   // importance = 0.003
   if ((inputValues[2]<-0.462438345)&&(0.7804290652<inputValues[3])) rval+=0.02171216919;   // importance = 0.003
   if ((-1.117463708<inputValues[0])&&(inputValues[1]<0.6006079316)&&(inputValues[2]<1.140246987)&&(inputValues[3]<-1.290628314)) rval+=-0.009453767893;   // importance = 0.002
   if ((-1.117463708<inputValues[0])&&(inputValues[1]<0.6006079316)&&(inputValues[3]<-1.290628314)) rval+=-0.009453767893;   // importance = 0.002
   //
   // here follows all linear terms
   // at the end of each line, the relative importance of the term is given
   //
   rval+=-0.2584084211*std::min( double(3.424694538), std::max( double(inputValues[0]), double(-3.420648575)));   // importance = 0.854
   rval+=-0.0810712059*std::min( double(2.155888557), std::max( double(inputValues[1]), double(-2.174304962)));   // importance = 0.170
   rval+=-0.0365194258*std::min( double(2.059992075), std::max( double(inputValues[2]), double(-2.086013556)));   // importance = 0.074
   rval+=0.4139454892*std::min( double(2.61591959), std::max( double(inputValues[3]), double(-2.359440565)));   // importance = 1.000
   return rval;
}
   inline double ReadRuleFit::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
