// Class: ReadMLPBNN
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLPBNN
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/09       [336393]
Creator        : rute
Date           : Sun Sep 11 13:55:54 2016
Host           : Linux ui6-atlas.lip.pt 2.6.32-358.6.2.el6.x86_64 #1 SMP Thu May 16 20:59:36 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /u/home/calo/rute/EstagioATLAScoded/TMVAproject
Training events: 6000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "60" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TrainingMethod: "BFGS" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "True" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 4
var1+var2                     myvar1                        myvar1                        myvar1                                                          'F'    [-8.96602058411,7.69307804108]
var1-var2                     myvar2                        myvar2                        Expression 2                                                    'F'    [-4.08540010452,4.0258936882]
var3                          var3                          var3                          Variable 3                    units                             'F'    [-5.05078554153,4.35967063904]
var4                          var4                          var4                          Variable 4                    units                             'F'    [-5.95050764084,4.92254400253]
NSpec 2
var1*2                        spec1                         spec1                         Spectator 1                   units                             'F'    [-9.91655540466,9.52782058716]
var1*3                        spec2                         spec2                         Spectator 2                   units                             'F'    [-14.874833107,14.2917308807]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLPBNN : public IClassifierReader {

 public:

   // constructor
   ReadMLPBNN( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLPBNN" ),
        fNvars( 4 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "var1+var2", "var1-var2", "var3", "var4" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLPBNN() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][4];
   double fMax_1[3][4];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[4];
   double fVmax[4];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[4];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[10][5];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][10];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLPBNN::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 5; fWeights[0] = new double[5]; 
   fLayerSize[1] = 10; fWeights[1] = new double[10]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.158971537965464;
   fWeightMatrix0to1[1][0] = 2.06681983011904;
   fWeightMatrix0to1[2][0] = 0.837970004098845;
   fWeightMatrix0to1[3][0] = 0.873462928381712;
   fWeightMatrix0to1[4][0] = -1.5864522691177;
   fWeightMatrix0to1[5][0] = -1.06658340419849;
   fWeightMatrix0to1[6][0] = -0.556601398066652;
   fWeightMatrix0to1[7][0] = 1.53483424023916;
   fWeightMatrix0to1[8][0] = -1.59170004018908;
   fWeightMatrix0to1[0][1] = -0.0869572971037235;
   fWeightMatrix0to1[1][1] = -1.46622440408843;
   fWeightMatrix0to1[2][1] = -0.566756214037127;
   fWeightMatrix0to1[3][1] = -0.762179087315412;
   fWeightMatrix0to1[4][1] = -0.107650237993409;
   fWeightMatrix0to1[5][1] = -0.276447638985866;
   fWeightMatrix0to1[6][1] = 0.388835070857261;
   fWeightMatrix0to1[7][1] = -0.157081241664104;
   fWeightMatrix0to1[8][1] = 1.67500024562838;
   fWeightMatrix0to1[0][2] = 0.459971029807304;
   fWeightMatrix0to1[1][2] = 1.29314188027914;
   fWeightMatrix0to1[2][2] = -0.580070263012218;
   fWeightMatrix0to1[3][2] = -1.17680007110168;
   fWeightMatrix0to1[4][2] = -0.0666967154123215;
   fWeightMatrix0to1[5][2] = -0.410670854267764;
   fWeightMatrix0to1[6][2] = -0.929856241363744;
   fWeightMatrix0to1[7][2] = -0.62766157063369;
   fWeightMatrix0to1[8][2] = 0.996588949001732;
   fWeightMatrix0to1[0][3] = -0.680375721971505;
   fWeightMatrix0to1[1][3] = -1.74304047352379;
   fWeightMatrix0to1[2][3] = 0.228844926833719;
   fWeightMatrix0to1[3][3] = 0.401310600913684;
   fWeightMatrix0to1[4][3] = 2.51614117056905;
   fWeightMatrix0to1[5][3] = 0.453886331685378;
   fWeightMatrix0to1[6][3] = 0.181757494849498;
   fWeightMatrix0to1[7][3] = -0.108359143889537;
   fWeightMatrix0to1[8][3] = -0.0997043864607432;
   fWeightMatrix0to1[0][4] = -1.36247676140665;
   fWeightMatrix0to1[1][4] = 2.01060481244605;
   fWeightMatrix0to1[2][4] = -1.01609825223884;
   fWeightMatrix0to1[3][4] = 0.980688317596008;
   fWeightMatrix0to1[4][4] = -0.241590801596272;
   fWeightMatrix0to1[5][4] = 1.00375385769443;
   fWeightMatrix0to1[6][4] = 2.13336831608987;
   fWeightMatrix0to1[7][4] = 1.76317437493503;
   fWeightMatrix0to1[8][4] = -1.18863432020652;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -1.28497897246218;
   fWeightMatrix1to2[0][1] = 0.44921698909759;
   fWeightMatrix1to2[0][2] = 0.343400533278002;
   fWeightMatrix1to2[0][3] = 1.20927633156248;
   fWeightMatrix1to2[0][4] = 1.44933507382359;
   fWeightMatrix1to2[0][5] = 1.05653103278915;
   fWeightMatrix1to2[0][6] = 1.11875204622575;
   fWeightMatrix1to2[0][7] = -1.21753340481082;
   fWeightMatrix1to2[0][8] = 0.656336973772306;
   fWeightMatrix1to2[0][9] = -1.80017188800488;
}

inline double ReadMLPBNN::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLPBNN::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLPBNN::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLPBNN::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLPBNN::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLPBNN::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = -5.05625915527;
   fMax_1[0][0] = 6.3994679451;
   fMin_1[1][0] = -8.96602058411;
   fMax_1[1][0] = 7.69307804108;
   fMin_1[2][0] = -8.96602058411;
   fMax_1[2][0] = 7.69307804108;
   fMin_1[0][1] = -4.08540010452;
   fMax_1[0][1] = 3.40126919746;
   fMin_1[1][1] = -3.67916750908;
   fMax_1[1][1] = 4.0258936882;
   fMin_1[2][1] = -4.08540010452;
   fMax_1[2][1] = 4.0258936882;
   fMin_1[0][2] = -3.18263268471;
   fMax_1[0][2] = 3.84756541252;
   fMin_1[1][2] = -5.05078554153;
   fMax_1[1][2] = 4.35967063904;
   fMin_1[2][2] = -5.05078554153;
   fMax_1[2][2] = 4.35967063904;
   fMin_1[0][3] = -2.99590206146;
   fMax_1[0][3] = 4.5351858139;
   fMin_1[1][3] = -5.95050764084;
   fMax_1[1][3] = 4.92254400253;
   fMin_1[2][3] = -5.95050764084;
   fMax_1[2][3] = 4.92254400253;
}

//_______________________________________________________________________
inline void ReadMLPBNN::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 4;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<4;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLPBNN::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLPBNN::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
